# syntax=docker/dockerfile:1.6
# =============================================================================
# ULOV+ backend — multi-stage image
# Base: python:3.8.10-slim (product constraint)
# =============================================================================

# ---- Stage 1: builder -------------------------------------------------------
FROM python:3.8-slim-bullseye AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_VERSION=1.8.3 \
    POETRY_HOME=/opt/poetry \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=true \
    POETRY_VIRTUALENVS_IN_PROJECT=true

# System deps for psycopg2, argon2-cffi, geoalchemy2
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libffi-dev \
    libssl-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/opt/poetry/bin:${PATH}"

WORKDIR /app
COPY pyproject.toml ./
# Lock file will be generated by CI; if present, use --sync.
COPY poetry.lock* ./

# Install prod deps only (dev deps installed in a separate dev image if needed)
RUN poetry install --no-root --only main

# ---- Stage 2: runtime -------------------------------------------------------
FROM python:3.8-slim-bullseye AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/app/.venv/bin:${PATH}" \
    APP_HOME=/app

# Runtime libs only (no build-essential)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    curl \
    tini \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --system ulov \
    && useradd --system --gid ulov --home-dir ${APP_HOME} --shell /usr/sbin/nologin ulov

WORKDIR ${APP_HOME}

COPY --from=builder /app/.venv /app/.venv
COPY --chown=ulov:ulov . .

USER ulov

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD curl -fsS http://localhost:8000/health/live || exit 1

# tini is PID 1 → forwards signals correctly, reaps zombies
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips", "*"]
