"""add_insurance_companies_v2

Revision ID: e52e9a810976
Revises: 0005_phase6_billing
Create Date: 2026-04-25 14:56:15.677661+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e52e9a810976'
down_revision: Union[str, None] = '0005_phase6_billing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_companies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reviews_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('base_price', sa.BigInteger(), nullable=False),
    sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('insurance_policies', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'insurance_policies', 'insurance_companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_mechanics_center_active', table_name='mechanics', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_mileage_readings_recorded_at', table_name='mileage_readings')
    op.drop_index('ix_notifications_read_at', table_name='notifications')
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_constraint('fk_reviews_center', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_service', 'reviews', type_='foreignkey')
    op.drop_index('ix_service_transitions_service_at', table_name='service_transitions')
    op.create_index(op.f('ix_service_transitions_service_id'), 'service_transitions', ['service_id'], unique=False)
    op.drop_index('ix_services_center_status', table_name='services')
    op.drop_index('ix_users_center_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_constraint('fk_users_center', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_center', 'users', 'service_centers', ['center_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_center_id', 'users', ['center_id'], unique=False)
    op.create_index('ix_services_center_status', 'services', ['center_id', 'status'], unique=False)
    op.drop_index(op.f('ix_service_transitions_service_id'), table_name='service_transitions')
    op.create_index('ix_service_transitions_service_at', 'service_transitions', ['service_id', sa.text('at DESC')], unique=False)
    op.create_foreign_key('fk_reviews_service', 'reviews', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_reviews_center', 'reviews', 'service_centers', ['center_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.create_index('ix_notifications_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index('ix_mileage_readings_recorded_at', 'mileage_readings', ['car_id', 'recorded_at'], unique=False)
    op.create_index('ix_mechanics_center_active', 'mechanics', ['center_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(None, 'insurance_policies', type_='foreignkey')
    op.drop_column('insurance_policies', 'company_id')
    op.drop_table('insurance_companies')
    # ### end Alembic commands ###
